[project]
name = "mcp1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "azure-kusto-data>=5.0.3",
    "click>=8.2.1",
    "mcp[mci]>=1.9.3",
]
